language: python
dist: bionic
python:
    - "3.6"
before_install:
    - sudo apt-get install -y libc6
install:
    - pip install -e .
    - pip install codecov
script:
    - python setup.py test
after_success:
    - codecov
